[agent]
name = "podcast_generator"
version = "0.0.1"

[options.OPENAI_API_KEY]
type = "string"
description = "OpenAI API key used for filtering data input"
default = "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"

[options.ELEVENLABS_API_KEY]
type = "string"
description = "ElevenLabs API key used for text-to-dialogue synthesis"
default = "sk_60a5b94428ddab05706d2aae77ad0394a4495329527df972"

[options.ELEVENLABS_OUTPUT_FORMAT]
type = "string"
description = "Override ElevenLabs output format"
default = "mp3_44100_128"

[options.ELEVENLABS_RETURN_BASE64]
type = "string"
description = "Return ElevenLabs audio as base64 when set to 1/true"
default = "0"

[options.MAX_INLINE_BYTES]
type = "string"
description = "Maximum inline base64 payload size in bytes"
default = "5242880"

[options.OUTPUT_DIR]
type = "string"
description = "Directory to write generated audio files"
default = "out"

[options.WAIT_TIMEOUT_MS]
type = "string"
description = "Mention wait timeout in milliseconds"
default = "600000"



[runtimes.executable]
command = ["npm", "run", "start"]
environment = [
    { option = "OPENAI_API_KEY"},
    { option = "ELEVENLABS_API_KEY" },
    { option = "ELEVENLABS_OUTPUT_FORMAT" },
    { option = "ELEVENLABS_RETURN_BASE64" },
    { option = "MAX_INLINE_BYTES" },
    { option = "OUTPUT_DIR" },
    { option = "WAIT_TIMEOUT_MS" },
]
